server:
  port: 8089
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'metrics'
  # https://www.baeldung.com/spring-liveness-readiness-probes
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true