apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: graceful
  name: graceful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graceful
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: graceful
    spec:
      containers:
        - image: qoosdd89382/graceful
          name: graceful
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
#            initialDelaySeconds: 120
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8089
          livenessProbe:
#            initialDelaySeconds: 120
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8089
status: {}