apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: graceful
  name: graceful
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: graceful
status:
  loadBalancer: {}